# Use an official Python runtime as a parent image
FROM gcr.io/google-appengine/python

RUN virtualenv /env -p python3.6

RUN . /env/bin/activate
# Set the working directory to /app
# WORKDIR /app

# Copy the current directory contents into the container at /app
# ADD . /app

# Install
# RUN apt-get update
# RUN apt-get install -y build-essential swig curl
# RUN apt-get install -y python3 python3-dev

RUN pip install --upgrade pip

RUN pip install --trusted-host pypi.python.org pyrfr
# RUN curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 pip install

# RUN pip install numpy
# RUN pip install -r requirements.txt

# Make port 80 available to the world outside this container
# EXPOSE 80

# Define environment variable
# ENV NAME World

# Run app.py when the container launches
# CMD gunicorn app:app -b :80 --workers 1 --timeout 120 --log-level debug
